### ISSUE TITLE
ImportError: No module named kaldi_io_internal

### ISSUE THREAD

**Issue by gxstudy** [dmitriy-serdyuk/kaldi-python#12]
Hi, @dmitriy-serdyuk ,

"import kaldi_io" gives me the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "kaldi_io/__init__.py", line 243, in <module>
    from kaldi_io_internal import *
ImportError: No module named kaldi_io_internal

Could you please help me solve it. Thank you so much.

Best,
Cindy

**Comment by dmitriy-serdyuk** [comment]
Try to check if there is `kaldi_io_internal.so` near `kaldi_io`. It should print in the traceback where is your kaldi_io installed. 

It may be a problem with installation, make sure that you have kaldi compiled with `--shared` and `KALDI_ROOT` points to your kaldi.

**Comment by ermu-tech** [comment]
> Try to check if there is `kaldi_io_internal.so` near `kaldi_io`. It should print in the traceback where is your kaldi_io installed.
> 
> It may be a problem with installation, make sure that you have kaldi compiled with `--shared` and `KALDI_ROOT` points to your kaldi.

excuse me ,where can I point KALDI_ROOT  to my kaldi?
