### ISSUE TITLE
ImportError: kaldi_io/kaldi_io_internal.so: undefined symbol: _ZN5kaldi9SemaphoreD1Ev

### ISSUE THREAD

**Issue by gray0302** [dmitriy-serdyuk/kaldi-python#16]
import kaldi_io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "kaldi_io/__init__.py", line 243, in <module>
    from kaldi_io_internal import *
ImportError: kaldi_io/kaldi_io_internal.so: undefined symbol: _ZN5kaldi9SemaphoreD1Ev
when I import kaldi_io, I encountered the problem. Could you help me solve it, thank you very much.

**Comment by dmitriy-serdyuk** [comment]
Check that you compiled a shared library for kaldi. Try to add it to your `LD_LIBRARY_PATH`.

**Comment by gray0302** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-1-73f710c68779> in <module>()
----> 1 import kaldi_io

/usr/lib/python2.7/site-packages/kaldi_io/__init__.py in <module>()
    241 
    242 import numpy as np
--> 243 from kaldi_io_internal import *
    244 
    245 if KALDI_BASE_FLOAT()==np.float64:

ImportError: /usr/lib/python2.7/site-packages/kaldi_io/kaldi_io_internal.so: undefined symbol: _ZN5kaldi9SemaphoreD1Ev

I add the kaldi_io_internal.so to  LD_LIBRARY_PATH, but the issue is still.

**Comment by dmitriy-serdyuk** [comment]
I can suggest to rebuild kaldi, maybe issue is there. Check if there were errors during the setup of kaldi-python (run it in verbose mode).

**Comment by YichiHuang** [comment]
I encountered the same problem. I rebuilt the kaldi with `configure --share`. And I also add the kaldi_io_internal.so to `python3.5/site-packages/`.
